name: dependabot-test
on:
  schedule:
    - cron: '*/5 * * * *' # every 6 hours
branches:
- 'dependabot/**'
jobs:
dependabot-test:
runs-on: ubuntu-20.04
name: Sends a message to Slack when a push, a pull request or an issues is made
steps:
- name: Send message to Slack API
uses: archive/github-actions-slack@v2.0.0
id: notify
with:
slack-bot-user-oauth-access-token: ${{ secrets.DEPENDABOT_SLACK_SECRET }}
slack-channel: "dependabot-test"
slack-text: New Dependabot PR ${{ github.event.pull_request.html_url }}
