name: dependabot-test

on: [push]

jobs:
  dependabot-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Sends a message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.DEPENDABOT_SLACK_SECRET }}
          slack-channel: C04NBK546KG
          slack-text: New Dependabot PR ${{ github.event.pull_request.html_url }}
          run: echo "${{ steps.send-message.outputs.slack-result }}"
