name: dependabot-test
on:
  push:
    branches:
      - 'main'
jobs:
  dependabot-test:
    runs-on: ubuntu-20.04
    steps:
      - name: 'dependabot-test'
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.DEPENDABOT_SLACK_SECRET }}
          slack-channel: 'dependabot-test'
          slack-text: New Dependabot PR ${{ github.event.pull_request.html_url }}
